name: Release (by Tag Push)

on:
  workflow_dispatch:
  release:
    type: [published]

jobs:
  pypi-publish:
    if: "!github.event.release.prerelease"
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ctdopts
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1